import {describe,it,expect,vi} from 'vitest';
import {POST as analyzePost} from '@/app/api/analyze/route';
import {POST as briefPost} from '@/app/api/brief/route';
import {ingestText,ingestFixture} from '@/lib/pipeline/ingest';
import {analyze} from '@/lib/pipeline/analyze';
import {analyzeWithOptionalLlm} from '@/lib/pipeline/optionalLlm';
import {validateUploadedFile} from '@/lib/pipeline/fileSafety';
import {demoCase} from '@/fixtures/demoCase';
function upload(files:File[],ip:string){const form=new FormData();files.forEach(f=>form.append('files',f));form.set('primaryIndex','0');return new Request('http://localhost/api/analyze',{method:'POST',headers:{'x-forwarded-for':ip},body:form});}
describe('hardening and sparse documents',()=>{
 it('rejects empty and mismatched files and detects encryption flags',async()=>{const empty=await analyzePost(upload([new File([],'empty.txt')],'empty-ip'));expect(empty.status).toBe(400);expect((await empty.json()).error).toContain('empty');await expect(analyzePost(upload([new File(['not PDF'],'fake.pdf')],'wrong-ip'))).resolves.toMatchObject({status:400});expect(()=>validateUploadedFile('locked.pdf',new TextEncoder().encode('%PDF-1.7 /Encrypt'))).toThrow(/encrypted/);});
 it('rejects oversized multipart bodies before parsing their contents',async()=>{const req=new Request('http://localhost/api/analyze',{method:'POST',headers:{'content-length':String(30*1024*1024),'x-forwarded-for':'huge-body-ip'},body:'small'});const response=await analyzePost(req);expect(response.status).toBe(413);});
 it('rejects the seventh file and an oversized file',async()=>{const seven=await analyzePost(upload(Array.from({length:7},(_,i)=>new File(['ok'],`file${i}.txt`)),'seven-ip'));expect(seven.status).toBe(413);const large=new File([new Uint8Array(10*1024*1024+1)],'large.txt');const response=await analyzePost(upload([large],'large-ip'));expect(response.status).toBe(413);});
 it('handles reports without references, authors or funding disclosure',()=>{const result=analyze([ingestText('sparse.txt','A short report describes an outcome without any author or reference list.','primary')]);expect(result.findings.some(f=>f.type==='funding_not_disclosed'&&f.label==='UNKNOWN')).toBe(true);expect(result.citations).toHaveLength(0);expect(result.entities.some(e=>e.type==='person')).toBe(false);});
 it('falls back after repeated LLM request failures',async()=>{vi.stubEnv('LLM_BASE_URL','https://llm.example/v1');vi.stubEnv('LLM_API_KEY','temporary-test');vi.stubEnv('LLM_MODEL','model');vi.stubEnv('OPENALEX_MAILTO','');vi.stubGlobal('fetch',vi.fn(async()=>{throw new Error('simulated timeout');}));try{const result=await analyzeWithOptionalLlm(ingestFixture(demoCase));expect(result.findings.some(f=>f.type==='funding_conflict')).toBe(true);expect(result.mode.llm).toBe(true);expect(result.privacy.externalCalls.some(c=>c.purpose.includes('failed'))).toBe(true);}finally{vi.unstubAllEnvs();vi.unstubAllGlobals();}});
 it('returns a friendly timeout response and records attempted voice processing',async()=>{vi.stubEnv('ELEVENLABS_API_KEY','temporary-test');vi.stubEnv('ELEVENLABS_VOICE_ID','voice-test');vi.stubGlobal('fetch',vi.fn(async()=>{throw new Error('simulated timeout');}));try{const response=await briefPost(new Request('http://localhost/api/brief',{method:'POST',headers:{'content-type':'application/json','x-forwarded-for':'brief-timeout-ip'},body:JSON.stringify({text:'Email person@example.org'})}));expect(response.status).toBe(504);const body=await response.json();expect(body.error).toContain('timed out');expect(body.privacy.redactions.email).toBe(1);}finally{vi.unstubAllEnvs();vi.unstubAllGlobals();}});
 it('runs two uploads at the same time with separate results',async()=>{const [a,b]=await Promise.all([analyzePost(upload([new File(['Report A states 22% completed work [1].\n[1] Source A'], 'a.txt')],'parallel-a')),analyzePost(upload([new File(['Report B states 54% completed work [1].\n[1] Source B'], 'b.txt')],'parallel-b'))]);expect(a.status).toBe(200);expect(b.status).toBe(200);const [ra,rb]=await Promise.all([a.json(),b.json()]);expect(ra.docs[0].fileName).toBe('a.txt');expect(rb.docs[0].fileName).toBe('b.txt');expect(ra.claims[0].text).not.toEqual(rb.claims[0].text);});
});
