import type {AnalysisResult,Claim,EvidenceRef,Finding,SourceDoc} from '../types';
import {scanHidden} from '../detectors/hiddenInstruction';
import {scoreFindings} from '../score';
import {lintLanguage} from '../lintLanguage';
import {AnalysisResultSchema} from '../types';
const ref=(doc:SourceDoc,quote:string,page=1):EvidenceRef=>({kind:'quote',docId:doc.id,fileName:doc.fileName,page,quote});
const finding=(type:Finding['type'],label:Finding['label'],severity:Finding['severity'],title:string,what:string,why:string,evidence:EvidenceRef[],recommendedActions=['Review the cited evidence and seek independent confirmation.'],uncertainty='This finding describes the available document evidence; it does not by itself establish that the findings are invalid.'):Finding=>{const seed=`${type}|${evidence.map(e=>`${e.fileName??e.url}:${e.page??''}:${e.quote??''}`).join('|')}`;let hash=2166136261;for(const char of seed){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return{id:`f-${type}-${(hash>>>0).toString(36)}`,type,label,severity,title,whatWasFound:what,whyItMatters:why,uncertainty,recommendedActions,evidence,graphNodeIds:[]};};
const visible=(d:SourceDoc)=>d.pages.map(p=>p.text.replace(/<!--[\s\S]*?-->/g,'')).join('\n');
export function validateFindings(fs:Finding[],docs:SourceDoc[]){return fs.filter(f=>f.evidence.length>0&&f.evidence.every(e=>e.kind==='record'?!!e.url:!!e.fileName&&!!e.quote&&!!e.page&&docs.some(d=>d.fileName===e.fileName&&(d.pages.some(p=>p.page===e.page&&p.text.includes(e.quote!))||(e.method==='file safety scan'&&d.safety.pdfFlags.includes(e.quote!)))))&&lintLanguage(f.title+f.whatWasFound+f.whyItMatters+f.uncertainty+f.recommendedActions.join(' ')));}
export function analyze(input:SourceDoc[]):AnalysisResult {
 const docs=scanHidden(input);const findings:Finding[]=[],claims:Claim[]=[],entities:AnalysisResult['entities']=[],relations:AnalysisResult['relations']=[],citations:AnalysisResult['citations']=[];
 for(const d of docs){if(!d.safety.typeMatchesExtension||d.safety.encrypted||d.safety.pdfFlags.length){const flags=[...(!d.safety.typeMatchesExtension?['File type does not match its extension.']:[]),...(d.safety.encrypted?['/Encrypt']:[]),...d.safety.pdfFlags];for(const flag of flags){const safetyRef:EvidenceRef={kind:'quote',docId:d.id,fileName:d.fileName,page:1,quote:flag,method:'file safety scan'};findings.push(finding('file_safety','POTENTIAL_CONCERN','medium','File safety flag detected',`${flag} was found in the uploaded file bytes.`,'Active PDF features can carry actions or embedded content. The document is treated as data only.',[safetyRef],['Review the file in a safe viewer and request a clean copy.']));}}}
 const primary=docs.find(d=>d.role==='primary')!;const text=visible(primary);const log:{stage:string;detail:string;ms:number}[]=[{stage:'ingest',detail:`Loaded ${docs.length} document(s) in memory.${docs.flatMap(d=>d.ingestNotes??[]).length?` ${docs.flatMap(d=>d.ingestNotes??[]).join(' ')}`:''}`,ms:0},{stage:'screen',detail:`Scanned ${docs.length} document(s) for hidden instructions.`,ms:1}];
 for(const d of docs)for(const h of d.hiddenSpans){const ev=[{kind:'quote' as const,docId:d.id,fileName:d.fileName,page:h.page,quote:h.text,method:h.method}];if(h.method==='visible instruction pattern')findings.push(finding('hidden_instruction','POTENTIAL_CONCERN','medium','Instruction pattern in visible text',`Visible text includes an instruction pattern: “${h.text}”`,'This text may be a legitimate visible discussion of prompt injection.',ev,['Check the surrounding discussion and source context.'],'This may be a legitimate visible discussion of prompt injection.'));else findings.push(finding('hidden_instruction','POTENTIAL_CONCERN','high','Hidden instruction detected',`Hidden text contains: “${h.text}”`,`Hidden instructions can try to influence automated review. The text is excluded from claim extraction.`,ev,['Inspect the revealed text and consider obtaining a clean copy.']));}
 const lines=text.split(/(?<=[.!?])\s+|\n+/).map(s=>s.trim()).filter(Boolean);
 const refRe=/^\[(\d+)\]\s*(.*)$/gm; for(const m of text.matchAll(refRe)){const title=m[2].replace(/["“”]/g,'').split(/,|\./)[0].trim();citations.push({key:m[1],rawText:m[0],title,refs:[ref(primary,m[0])]});}
 for(const line of lines){if(line.length<25||/^#|^Authors:|^FICTIONAL|^\[\d+\]/.test(line))continue;const refs=[...line.matchAll(/\[(\d+)\]/g)].map(m=>m[1]);if(/\d+%|\bn\s*=\s*\d+/i.test(line)){claims.push({id:`claim-${claims.length+1}`,text:line,statistic:line.match(/\d+%|\bn\s*=\s*\d+/i)?.[0],citationKeys:refs,causalLanguage:/improv|cause|increase|reduce|lead to/i.test(line),generalizes:/everywhere|all workers|universally|people in general/i.test(line),refs:[ref(primary,line)]});}}
 const methods=text.match(/We surveyed[^\n]+/i)?.[0]; const sample=methods?.match(/surveyed\s+(\d+)\s+employees/i); const single=/single\s+(?:logistics\s+)?company|employees of/i.test(methods??''); const design=/survey|surveyed|questionnaire/i.test(text)?'survey':/randomized|randomly assigned|control group/i.test(text)?'experiment':'unknown';
 const fund=text.match(/(?:supported by a grant from|funded by|grant from|Funding[^\n]*\n)([^.\n]+(?:Corp\.)?)/i)?.[0]; const sell=text.match(/TaskNimbus is (?:developed and sold|sold|owned|developed) by [^.]+\./i)?.[0];
 const title=(text.match(/^#\s*(.+)$/m)?.[1]??primary.fileName);const author=text.match(/Authors?:\s*([^\n]+)/i)?.[1];const org=text.match(/\n(Tellenby Workplace Institute|[^\n]*Institute)\n/mi)?.[1];
 const ent=(name:string,type:AnalysisResult['entities'][number]['type'],q:string)=>{let x=entities.find(e=>e.name===name);if(!x){x={id:`e-${entities.length+1}`,type,name,aliases:[],refs:[ref(primary,q)]};entities.push(x);}return x;};
 const titleEnt=ent(title,'document',`# ${title}`);let authorEnt;if(author){authorEnt=ent(author,'person',`Authors: ${author}`);relations.push({from:authorEnt.id,to:titleEnt.id,type:'authored',refs:[ref(primary,`Authors: ${author}`)]});}
 if(org){const oe=ent(org,'organization',org);if(authorEnt)relations.push({from:authorEnt.id,to:oe.id,type:'affiliated_with',refs:[ref(primary,org)]});findings.push(finding('affiliation_documented','FACT','info','Author affiliation documented',`${author??'The listed author'} is affiliated with ${org}.`,'Affiliations can help readers understand the context of the work.',[ref(primary,org)]));}
 if(fund&&sell){const fundName=fund.match(/(?:from|by)\s+(.+)$/i)?.[1]?.replace(/\.$/,'')??fund;const fe=ent(fundName,'funder',fund),pe=ent('TaskNimbus','product',sell);relations.push({from:fe.id,to:pe.id,type:'sells',refs:[ref(primary,sell)]},{from:fe.id,to:titleEnt.id,type:'funded_by',refs:[ref(primary,fund)]});findings.push(finding('funding_conflict','POTENTIAL_CONCERN','medium','Potential conflict identified',`${fundName} funded the study and is described as selling TaskNimbus.`,'A documented financial relationship is relevant context when assessing independence.',[ref(primary,fund),ref(primary,sell)],['Review independent evaluations and the funder’s role in study design and reporting.']));}
 else if(!/funding|acknowledg|conflict of interest/i.test(text))findings.push(finding('funding_not_disclosed','UNKNOWN','low','Funding statement not found','No funding or conflict-of-interest statement was identified in the visible text.','Funding details can help readers assess the study context.',[ref(primary,text.slice(0,Math.min(text.length,60))) ]));
 if(sample&&single){const q=methods!;findings.push(finding('sampling_limitation','POTENTIAL_CONCERN','medium','Sampling limitation identified',`The study surveyed ${sample[1]} employees at a single organization.`,'A sample from one organization may not represent other workplaces.',[ref(primary,q)]));}
 const refsByKey=new Map(citations.map(c=>[c.key,c]));const sources=docs.filter(d=>d.role==='cited');const matched=sources.map(d=>({doc:d,title:d.pages[0]?.text.match(/^#\s*(.+)$/m)?.[1]??'',root:d.pages[0]?.text.match(/data comes from the ([^.]+)/i)?.[1]??d.fileName}));
 for(const c of citations){const hit=matched.find(m=>m.title.toLowerCase()===c.title?.toLowerCase());if(hit)c.matchedDocId=hit.doc.id;}
 const mainClaim=claims.find(c=>c.citationKeys.length>=4); if(mainClaim){const chain=mainClaim.citationKeys.map(k=>refsByKey.get(k)).filter(Boolean);const used=chain.map(c=>matched.find(m=>m.doc.id===c?.matchedDocId)).filter(Boolean);if(used.length>=2){const roots=[...new Set(used.map(m=>m!.root))];if(roots.length<used.length){const shared=used.find(m=>used.filter(n=>n?.root===m!.root).length>=2)!;const ev=[mainClaim.refs[0],...used.map(m=>ref(m!.doc,m!.doc.pages[0].text.match(/data comes from[^.]+\./i)?.[0]??m!.doc.pages[0].text.split('\n')[0]))];findings.push(finding('evidence_dependency','POTENTIAL_CONCERN','medium','Evidence dependency identified',`${used.length} cited sources trace back to ${roots.length} underlying sources; ${shared.root} is shared by multiple sources.`,'Several citations may rely on overlapping data, reducing the apparent independence of the evidence.',ev));}}
 }
 for(const c of claims){const matchedKeys=c.citationKeys.map(k=>refsByKey.get(k)).filter(x=>x?.matchedDocId);if(c.statistic&&(!c.citationKeys.length||matchedKeys.length===0)){findings.push(finding('untraced_statistic','UNKNOWN','low','Statistic could not be independently traced',`The statistic “${c.statistic}” has no matched uploaded source.`,'A traceable source makes it easier to check how a statistic was produced.',[...c.refs]));}if(c.causalLanguage&&design==='survey'){findings.push(finding('causal_language','INTERPRETATION','info','Causal wording in survey research',`The claim uses causal wording (“improves”) while the described design is a survey.`,'Survey designs can show reported associations, but usually cannot establish causation by themselves.',c.refs));}}
 const methodology={sampleSize:sample?Number(sample[1]):undefined,recruitmentScope:methods,singleSite:single,design:design as 'experiment'|'observational'|'survey'|'unknown',statedLimitations:[],refs:methods?[ref(primary,methods)]:[]};
 docs.forEach(d=>{for(const h of d.hiddenSpans)if(h.method!=='visible instruction pattern'){const found=findings.find(f=>f.type==='hidden_instruction'&&f.evidence[0]?.fileName===d.fileName&&f.evidence[0]?.page===h.page);if(found)found.graphNodeIds.push(d.id);}});
 const visibleFindings=validateFindings(findings,docs);const score=scoreFindings(visibleFindings);log.push({stage:'extract',detail:`Extracted ${claims.length} claims and ${citations.length} citations.`,ms:2},{stage:'detect',detail:`Validated ${visibleFindings.length} findings against exact evidence.`,ms:1},{stage:'score',detail:'Applied deterministic category deductions.',ms:1},{stage:'validate',detail:`Dropped ${findings.length-visibleFindings.length} unsupported findings.`,ms:1});
 const rootEntities=new Map<string,string>();for(const m of matched){const quote=m.doc.pages[0]?.text.match(/data comes from[^.]+\./i)?.[0];if(!quote)continue;let dataset=entities.find(e=>e.type==='dataset'&&e.name===m.root);if(!dataset)dataset=ent(m.root,'dataset',quote);rootEntities.set(m.doc.id,dataset.id);relations.push({from:`doc-${m.doc.id}`,to:dataset.id,type:'derived_from',refs:[ref(m.doc,quote)]});}
 const laneCounts=new Map<string,number>();const place=(lane:string,x:number)=>{const y=(laneCounts.get(lane)??0)*115;laneCounts.set(lane,y/115+1);return{x,y};};
 const nodes=[...docs.map(d=>({id:`doc-${d.id}`,type:'evidenceNode',position:place(d.role==='primary'?'primary':'cited',d.role==='primary'?0:760),data:{label:d.fileName,kind:'document'}})),...entities.map(e=>({id:e.id,type:'evidenceNode',position:place(e.type==='dataset'?'root':'entity',e.type==='dataset'?1080:250),data:{label:e.name,kind:e.type,shared:e.type==='dataset'&&matched.filter(m=>m.root===e.name).length>1}})),...claims.map(c=>({id:c.id,type:'evidenceNode',position:place('claim',510),data:{label:c.text.slice(0,80),kind:'claim'}})),...citations.map(c=>({id:`cite-${c.key}`,type:'evidenceNode',position:place('citation',780),data:{label:c.title??c.rawText,kind:'citation'}}))];
 const edges:{id:string;source:string;target:string;label:string}[]=relations.map((r,i)=>({id:`edge-${i}`,source:r.from,target:r.to,label:r.type}));for(const c of claims)for(const key of c.citationKeys){const cite=refsByKey.get(key);if(cite){edges.push({id:`claim-cite-${c.id}-${key}`,source:c.id,target:`cite-${key}`,label:'cites'});if(cite.matchedDocId)edges.push({id:`cite-doc-${key}`,source:`cite-${key}`,target:`doc-${cite.matchedDocId}`,label:'matched source'});}}
 for(const f of findings){const ids=new Set<string>();for(const e of f.evidence){const d=docs.find(x=>x.id===e.docId||x.fileName===e.fileName);if(d)ids.add(`doc-${d.id}`);for(const entity of entities)if(entity.refs.some(r=>r.fileName===e.fileName&&r.quote===e.quote))ids.add(entity.id);for(const claim of claims)if(claim.refs.some(r=>r.fileName===e.fileName&&r.quote===e.quote)){ids.add(claim.id);for(const key of claim.citationKeys){ids.add(`cite-${key}`);const citation=refsByKey.get(key);if(citation?.matchedDocId){ids.add(`doc-${citation.matchedDocId}`);const root=rootEntities.get(citation.matchedDocId);if(root)ids.add(root);}}}}f.graphNodeIds=[...ids];}
 return AnalysisResultSchema.parse({docs,entities,relations,claims,citations,methodology,findings:visibleFindings,graph:{nodes,edges},score,labLog:log,privacy:{stored:false,externalCalls:[],statement:'Nothing was stored.'},mode:{llm:false,publicRecords:false,voice:!!process.env.ELEVENLABS_API_KEY}});
}
