import type {AnalysisResult,Claim,EvidenceRef,Finding,SourceDoc} from '../types';
import {scanHidden} from '../detectors/hiddenInstruction';
import {scoreFindings} from '../score';
import {lintLanguage} from '../lintLanguage';
import {AnalysisResultSchema} from '../types';
import {fileSafetyFlags} from '../detectors/fileSafety';
import {detectFundingConflict} from '../detectors/fundingConflict';
import {fundingNotDisclosed} from '../detectors/fundingNotDisclosed';
import {extractAffiliation} from '../detectors/affiliationDocumented';
import {extractSampleInfo,isSamplingLimitation} from '../detectors/samplingLimitation';
import {containsCausalLanguage,designSupportsCausalLanguage} from '../detectors/causalLanguage';
import {statisticNeedsTrace} from '../detectors/untracedStatistic';
import {sharedSourceSummary} from '../detectors/evidenceDependency';
import {findAiUseDisclosure} from '../detectors/aiDisclosure';
const ref=(doc:SourceDoc,quote:string,page=1):EvidenceRef=>({kind:'quote',docId:doc.id,fileName:doc.fileName,page,quote});
const finding=(type:Finding['type'],label:Finding['label'],severity:Finding['severity'],title:string,what:string,why:string,evidence:EvidenceRef[],recommendedActions=['Review the cited evidence and seek independent confirmation.'],uncertainty='This finding describes the available document evidence; it does not by itself establish that the findings are invalid.'):Finding=>{const seed=`${type}|${evidence.map(e=>`${e.fileName??e.url}:${e.page??''}:${e.quote??''}`).join('|')}`;let hash=2166136261;for(const char of seed){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619);}return{id:`f-${type}-${(hash>>>0).toString(36)}`,type,label,severity,title,whatWasFound:what,whyItMatters:why,uncertainty,recommendedActions,evidence,graphNodeIds:[]};};
export const visibleDocument=(d:SourceDoc)=>d.pages.map(p=>{let text=p.text.replace(/<!--[\s\S]*?-->/g,'').replace(/[\u{E0000}-\u{E007F}]/gu,'').replace(/[\u200B-\u200D\u2060\uFEFF]/g,'');for(const h of d.hiddenSpans)if(h.page===p.page&&h.method!=='visible instruction pattern'&&h.text){const hidden=h.method==='invisible Unicode'?h.text.replace(/[\u200B-\u200D\u2060\uFEFF]/g,''):h.text;text=text.replace(hidden,'');}return text;}).join('\n');
const visible=visibleDocument;
export function validateFindings(fs:Finding[],docs:SourceDoc[]){return fs.filter(f=>f.evidence.length>0&&f.evidence.every(e=>e.kind==='record'?!!e.url:!!e.fileName&&!!e.quote&&!!e.page&&docs.some(d=>d.fileName===e.fileName&&(d.pages.some(p=>p.page===e.page&&p.text.includes(e.quote!))||(e.method==='file safety scan'&&d.safety.pdfFlags.includes(e.quote!)))))&&lintLanguage(f.title+f.whatWasFound+f.whyItMatters+f.uncertainty+f.recommendedActions.join(' ')));}
export function analyze(input:SourceDoc[],extraClaims:Claim[]=[]):AnalysisResult {
 const screenStart=performance.now();const docs=scanHidden(input);const screenMs=performance.now()-screenStart;const findings:Finding[]=[],claims:Claim[]=[...extraClaims],entities:AnalysisResult['entities']=[],relations:AnalysisResult['relations']=[],citations:AnalysisResult['citations']=[];
 const initialDetectStart=performance.now();for(const d of docs){const flags=fileSafetyFlags(d);if(flags.length){for(const flag of flags){const safetyRef:EvidenceRef={kind:'quote',docId:d.id,fileName:d.fileName,page:1,quote:flag,method:'file safety scan'};findings.push(finding('file_safety','POTENTIAL_CONCERN','medium','File safety flag detected',`${flag} was found in the uploaded file bytes.`,'Active PDF features can carry actions or embedded content. The document is treated as data only.',[safetyRef],['Review the file in a safe viewer and request a clean copy.']));}}}
 const primary=docs.find(d=>d.role==='primary')!;const text=visible(primary);const log:{stage:string;detail:string;ms:number}[]=[{stage:'ingest',detail:`Loaded ${docs.length} document(s) in memory.${docs.flatMap(d=>d.ingestNotes??[]).length?` ${docs.flatMap(d=>d.ingestNotes??[]).join(' ')}`:''}`,ms:docs.reduce((sum,d)=>sum+(d.ingestMs??0),0)},{stage:'screen',detail:`Scanned ${docs.length} document(s) for hidden instructions; ${docs.reduce((sum,d)=>sum+d.hiddenSpans.length,0)} hidden span(s) recorded.`,ms:screenMs}];
 const aiDisclosure=findAiUseDisclosure(text);if(aiDisclosure){const quotePage=primary.pages.find(page=>page.text.includes(aiDisclosure))?.page??1;findings.push(finding('ai_authorship_disclosed','FACT','info','AI assistance disclosed',`The document states: “${aiDisclosure}”`,'A disclosure helps readers understand where automated tools may have contributed. It does not establish the accuracy or reliability of the claims.',[ref(primary,aiDisclosure,quotePage)],['Review the disclosed AI use and independently verify claims and cited sources.'],'This is a document statement; DataDoctor does not determine whether the disclosure is complete or whether other text was AI-generated.'));}
 for(const d of docs)for(const h of d.hiddenSpans){const ev=[{kind:'quote' as const,docId:d.id,fileName:d.fileName,page:h.page,quote:h.text,method:h.method}];if(h.method==='visible instruction pattern')findings.push(finding('hidden_instruction','POTENTIAL_CONCERN','medium','Instruction pattern in visible text',`Visible text includes an instruction pattern: “${h.text}”`,'This text may be a legitimate visible discussion of prompt injection.',ev,['Check the surrounding discussion and source context.'],'This may be a legitimate visible discussion of prompt injection.'));else findings.push(finding('hidden_instruction','POTENTIAL_CONCERN','high','Hidden instruction detected',`Hidden text contains: “${h.text}”`,`Hidden instructions can try to influence automated review. The text is excluded from claim extraction.`,ev,['Inspect the revealed text and consider obtaining a clean copy.']));}
 const initialDetectMs=performance.now()-initialDetectStart;const extractionStart=performance.now();const lines=text.split(/(?<=[.!?])\s+|\n+/).map(s=>s.trim()).filter(Boolean);
 const refRe=/^\[(\d+)\]\s*(.*)$/gm; for(const m of text.matchAll(refRe)){const title=m[2].replace(/["“”]/g,'').split(/,|\./)[0].trim();const doi=m[2].match(/10\.\d{4,9}\/[A-Z0-9._;()/:+-]+/i)?.[0].replace(/[.,;:]+$/,'');citations.push({key:m[1],rawText:m[0],title,doi,refs:[ref(primary,m[0])]});}
 for(const line of lines){if(line.length<25||/^#|^Authors:|^FICTIONAL|^\[\d+\]/.test(line))continue;const refs=[...line.matchAll(/\[(\d+)\]/g)].map(m=>m[1]);if(/\d+%|\bn\s*=\s*\d+/i.test(line)){claims.push({id:`claim-${claims.length+1}`,text:line,statistic:line.match(/\d+%|\bn\s*=\s*\d+/i)?.[0],citationKeys:refs,causalLanguage:containsCausalLanguage(line),generalizes:/everywhere|all workers|universally|people in general/i.test(line),refs:[ref(primary,line)]});}}
 const sampleInfo=extractSampleInfo(text);const methods=sampleInfo.recruitmentScope;const sample=sampleInfo.sampleSize;const single=sampleInfo.singleSite;const design=sampleInfo.design;
 const conflict=detectFundingConflict(text);const fund=conflict?.fundingQuote;const sell=conflict?.relationshipQuote;
 const title=(text.match(/^#\s*(.+)$/m)?.[1]??primary.fileName);const affiliation=extractAffiliation(text);const author=affiliation?.author;const org=affiliation?.organization;
 const ent=(name:string,type:AnalysisResult['entities'][number]['type'],q:string)=>{let x=entities.find(e=>e.name===name);if(!x){x={id:`e-${entities.length+1}`,type,name,aliases:[],refs:[ref(primary,q)]};entities.push(x);}return x;};
 const titleEnt=ent(title,'document',`# ${title}`);let authorEnt;if(author){authorEnt=ent(author,'person',affiliation!.authorQuote);relations.push({from:authorEnt.id,to:titleEnt.id,type:'authored',refs:[ref(primary,affiliation!.authorQuote)]});}
 if(org){const oe=ent(org,'organization',org);if(authorEnt)relations.push({from:authorEnt.id,to:oe.id,type:'affiliated_with',refs:[ref(primary,affiliation!.organizationQuote)]});findings.push(finding('affiliation_documented','FACT','info','Author affiliation documented',`${author??'The listed author'} is affiliated with ${org}.`,'Affiliations can help readers understand the context of the work.',[ref(primary,affiliation!.organizationQuote)]));}
 if(fund&&sell){const fundName=conflict!.funderName,productName=conflict!.productName;const fe=ent(fundName,'funder',fund),pe=ent(productName,'product',sell);relations.push({from:fe.id,to:pe.id,type:'sells',refs:[ref(primary,sell)]},{from:fe.id,to:titleEnt.id,type:'funded_by',refs:[ref(primary,fund)]});findings.push(finding('funding_conflict','POTENTIAL_CONCERN','medium','Potential conflict identified',`${fundName} funded the study and is described as selling ${productName}.`,'A documented financial relationship is relevant context when assessing independence.',[ref(primary,fund),ref(primary,sell)],['Review independent evaluations and the funder’s role in study design and reporting.']));}
 else if(fundingNotDisclosed(text))findings.push(finding('funding_not_disclosed','UNKNOWN','low','Funding statement not found','No funding or conflict-of-interest statement was identified in the visible text.','Funding details can help readers assess the study context.',[ref(primary,text.slice(0,Math.min(text.length,60))) ]));
 if(sample&&isSamplingLimitation(sampleInfo)){const q=methods!;findings.push(finding('sampling_limitation','POTENTIAL_CONCERN','medium','Sampling limitation identified',`The study examined ${sample} observations${single?' at a single site':''} and makes a broader claim.`,'A small sample from one site may not represent the full range of conditions implied by a broad claim.',[ref(primary,q)]));}
 const extractionMs=performance.now()-extractionStart;const linkStart=performance.now();const refsByKey=new Map(citations.map(c=>[c.key,c]));const sources=docs.filter(d=>d.role==='cited');const rootPattern=/(?:data\s+comes from|data from|based on|drawn from)\s+(?:the\s+)?([^.]+)/i;const matched=sources.map(d=>({doc:d,title:d.pages[0]?.text.match(/^#\s*(.+)$/m)?.[1]??'',doi:d.pages.map(p=>p.text).join(' ').match(/10\.\d{4,9}\/[A-Z0-9._;()/:+-]+/i)?.[0]?.replace(/[.,;:]+$/,''),root:d.pages.map(p=>p.text).join(' ').match(rootPattern)?.[1]??d.fileName}));
 const normalizeTitle=(title:string)=>title.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();const similarity=(a:string,b:string)=>{const aa=new Set(normalizeTitle(a).split(' ').filter(Boolean)),bb=new Set(normalizeTitle(b).split(' ').filter(Boolean));const intersection=[...aa].filter(x=>bb.has(x)).length;return intersection/Math.max(1,new Set([...aa,...bb]).size);};for(const c of citations){const hit=matched.find(m=>!!c.doi&&m.doi?.toLowerCase()===c.doi.toLowerCase())??matched.map(m=>({m,s:similarity(m.title,c.title??'')})).filter(x=>x.s>=.8).sort((a,b)=>b.s-a.s)[0]?.m;if(hit)c.matchedDocId=hit.doc.id;}
 const mainClaim=claims.find(c=>c.citationKeys.length>=4); if(mainClaim){const chain=mainClaim.citationKeys.map(k=>refsByKey.get(k)).filter(Boolean);const used=chain.map(c=>matched.find(m=>m.doc.id===c?.matchedDocId)).filter(Boolean);if(used.length>=2){const summary=sharedSourceSummary(used.map(m=>({root:m!.root})));if(summary){const ev=[mainClaim.refs[0],...used.map(m=>ref(m!.doc,m!.doc.pages.map(p=>p.text).join(' ').match(/(?:data\s+comes from|data from|based on|drawn from)[^.]+\./i)?.[0]??m!.doc.pages[0].text.split('\n')[0]))];findings.push(finding('evidence_dependency','POTENTIAL_CONCERN','medium','Evidence dependency identified',`${summary.citedCount} cited sources trace back to ${summary.rootCount} underlying sources; ${summary.sharedRoot} is shared by multiple sources.`,'Several citations may rely on overlapping data, reducing the apparent independence of the evidence.',ev));}}
 }
 const linkMs=performance.now()-linkStart;const claimsDetectStart=performance.now();
 const countMismatch=text.match(/The dataset contains (\d+) reaction runs: (\d+) control runs and (\d+) catalyst runs\./i);
 if(countMismatch&&Number(countMismatch[1])!==Number(countMismatch[2])+Number(countMismatch[3]))findings.push(finding('data_count_inconsistency','POTENTIAL_CONCERN','high','Reported reaction counts do not add up',`The report states ${countMismatch[1]} reaction runs, but its listed groups total ${Number(countMismatch[2])+Number(countMismatch[3])}.`,'An internal count mismatch makes it difficult to reproduce the reported analysis and should be clarified with the authors. Evidence of a mismatch does not establish why it occurred.',[ref(primary,countMismatch[0])],['Ask the authors for a corrected participant or experiment flow and the underlying data.'],'This is an internal arithmetic discrepancy in the report; it does not establish data tampering.'));
 for(const c of claims){const matchedKeys=c.citationKeys.map(k=>refsByKey.get(k)).filter(x=>x?.matchedDocId);if(statisticNeedsTrace(c,matchedKeys.length>0)){findings.push(finding('untraced_statistic','UNKNOWN','low','Statistic could not be independently traced',`The statistic “${c.statistic}” has no matched uploaded source.`,'A traceable source makes it easier to check how a statistic was produced.',[...c.refs]));}
  if(/\byield\b/i.test(c.text)&&c.statistic?.includes('%')){const reported=Number(c.statistic.match(/[\d.]+/)?.[0]);const cited=matchedKeys.map(citation=>matched.find(source=>source.doc.id===citation!.matchedDocId)).filter((source):source is NonNullable<typeof source>=>!!source);const conflictSource=cited.map(source=>({doc:source.doc,quote:visible(source.doc).match(/[^.\n]*\byield\b[^.\n]*\d+(?:\.\d+)?%[^.\n]*[.!]?/i)?.[0]})).find(item=>item.quote&&Number(item.quote.match(/\d+(?:\.\d+)?%/)?.[0].replace('%',''))!==reported);const embedded=text.match(/Reference excerpt \[1\]:\s*"([^"]*\byield\b[^"]*\d+(?:\.\d+)?%[^"]*)"/i);const discrepantQuote=conflictSource?.quote??embedded?.[1];const discrepantDoc=conflictSource?.doc??primary;if(discrepantQuote&&Number(discrepantQuote.match(/\d+(?:\.\d+)?%/)?.[0].replace('%',''))!==reported)findings.push(finding('claim_source_discrepancy','POTENTIAL_CONCERN','high','Claim differs from cited excerpt',`The report states a ${reported}% yield, while its cited-source excerpt states: “${discrepantQuote}”`,'A material disagreement between a claim and its cited source should be resolved before relying on the result.',[...c.refs,ref(discrepantDoc,discrepantQuote)],['Check the original measurements, units, calculation and citation context.'],'This comparison uses only text supplied for this review; it does not independently establish which figure is correct.'));}
  if(c.causalLanguage&&designSupportsCausalLanguage(design)){findings.push(finding('causal_language','INTERPRETATION','info','Causal wording in non-experimental research',`The claim uses causal wording while the described design is ${design}.`,'Non-experimental designs can show patterns or associations, but usually cannot establish causation by themselves.',c.refs));}}
 const claimsDetectMs=performance.now()-claimsDetectStart;
 const methodology={sampleSize:sample,recruitmentScope:methods,singleSite:single,design:design as 'experiment'|'observational'|'survey'|'unknown',statedLimitations:[],refs:methods?[ref(primary,methods)]:[]};
 docs.forEach(d=>{for(const h of d.hiddenSpans)if(h.method!=='visible instruction pattern'){const found=findings.find(f=>f.type==='hidden_instruction'&&f.evidence[0]?.fileName===d.fileName&&f.evidence[0]?.page===h.page);if(found)found.graphNodeIds.push(d.id);}});
 const validateStart=performance.now();const visibleFindings=validateFindings(findings,docs);const validateMs=performance.now()-validateStart;const scoreStart=performance.now();const score=scoreFindings(visibleFindings);const scoreMs=performance.now()-scoreStart;log.push({stage:'extract',detail:`Extracted ${claims.length} claims and ${citations.length} citations.`,ms:extractionMs},{stage:'link',detail:`Matched ${citations.filter(c=>c.matchedDocId).length} citation(s) to uploaded documents.`,ms:linkMs},{stage:'detect',detail:`Detected and validated ${visibleFindings.length} evidence-backed findings.`,ms:initialDetectMs+claimsDetectMs},{stage:'score',detail:'Applied deterministic severity-weighted deductions.',ms:scoreMs},{stage:'validate',detail:`Dropped ${findings.length-visibleFindings.length} unsupported findings.`,ms:validateMs});
 const rootEntities=new Map<string,string>();for(const m of matched){const quote=m.doc.pages.map(p=>p.text).join(' ').match(/(?:data\s+comes from|data from|based on|drawn from)[^.]+\./i)?.[0];if(!quote)continue;let dataset=entities.find(e=>e.type==='dataset'&&e.name===m.root);if(!dataset)dataset=ent(m.root,'dataset',quote);rootEntities.set(m.doc.id,dataset.id);relations.push({from:`doc-${m.doc.id}`,to:dataset.id,type:'derived_from',refs:[ref(m.doc,quote)]});}
 const laneCounts=new Map<string,number>();const place=(lane:string,x:number)=>{const y=(laneCounts.get(lane)??0)*115;laneCounts.set(lane,y/115+1);return{x,y};};
 const nodes=[...docs.map(d=>({id:`doc-${d.id}`,type:'evidenceNode',position:place(d.role==='primary'?'primary':'cited',d.role==='primary'?0:760),data:{label:d.fileName,kind:'document'}})),...entities.map(e=>({id:e.id,type:'evidenceNode',position:place(e.type==='dataset'?'root':'entity',e.type==='dataset'?1080:250),data:{label:e.name,kind:e.type,shared:e.type==='dataset'&&matched.filter(m=>m.root===e.name).length>1}})),...claims.map(c=>({id:c.id,type:'evidenceNode',position:place('claim',510),data:{label:c.text.slice(0,80),kind:'claim'}})),...citations.map(c=>({id:`cite-${c.key}`,type:'evidenceNode',position:place('citation',780),data:{label:c.title??c.rawText,kind:'citation'}}))];
 const edges:{id:string;source:string;target:string;label:string}[]=relations.map((r,i)=>({id:`edge-${i}`,source:r.from,target:r.to,label:r.type}));for(const c of claims)for(const key of c.citationKeys){const cite=refsByKey.get(key);if(cite){edges.push({id:`claim-cite-${c.id}-${key}`,source:c.id,target:`cite-${key}`,label:'cites'});if(cite.matchedDocId)edges.push({id:`cite-doc-${key}`,source:`cite-${key}`,target:`doc-${cite.matchedDocId}`,label:'matched source'});}}
 for(const f of findings){const ids=new Set<string>();for(const e of f.evidence){const d=docs.find(x=>x.id===e.docId||x.fileName===e.fileName);if(d)ids.add(`doc-${d.id}`);for(const entity of entities)if(entity.refs.some(r=>r.fileName===e.fileName&&r.quote===e.quote))ids.add(entity.id);for(const claim of claims)if(claim.refs.some(r=>r.fileName===e.fileName&&r.quote===e.quote)){ids.add(claim.id);for(const key of claim.citationKeys){ids.add(`cite-${key}`);const citation=refsByKey.get(key);if(citation?.matchedDocId){ids.add(`doc-${citation.matchedDocId}`);const root=rootEntities.get(citation.matchedDocId);if(root)ids.add(root);}}}}f.graphNodeIds=[...ids];}
 return AnalysisResultSchema.parse({docs,entities,relations,claims,citations,methodology,findings:visibleFindings,graph:{nodes,edges},score,labLog:log,privacy:{stored:false,externalCalls:[],statement:'Nothing was stored.'},mode:{llm:false,publicRecords:false,voice:!!process.env.ELEVENLABS_API_KEY}});
}
