import type {AnalysisResult,EvidenceRef} from '../types';
import {scoreFindings} from '../score';
import {validateFindings} from './analyze';
type Json=Record<string,unknown>;
type WorkResult={crossref:Json|null;openalex:Json|null;urls:{crossref:string;openalex:string}};
const cache=new Map<string,{at:number;value:Promise<WorkResult>}>();
function obj(value:unknown):Json{return value&&typeof value==='object'?value as Json:{}}
function array(value:unknown):unknown[]{return Array.isArray(value)?value:[]}
function str(value:unknown){return typeof value==='string'?value:''}
async function getJson(url:string):Promise<Json|null>{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),5000);try{const response=await fetch(url,{signal:controller.signal,headers:{accept:'application/json'}});if(!response.ok)return null;return obj(await response.json());}catch{return null;}finally{clearTimeout(timer);}}
function getWork(doi:string,mailto:string):Promise<WorkResult>{const key=doi.toLowerCase();const saved=cache.get(key);if(saved&&Date.now()-saved.at<10*60_000)return saved.value;const crossref=`https://api.crossref.org/works/${encodeURIComponent(doi)}`;const openalex=`https://api.openalex.org/works/https://doi.org/${doi}?mailto=${encodeURIComponent(mailto)}`;const value=Promise.all([getJson(crossref),getJson(openalex)]).then(([c,o])=>({crossref:c,openalex:o,urls:{crossref,openalex}}));cache.set(key,{at:Date.now(),value});return value;}
const recordRef=(source:'crossref'|'openalex',url:string,note:string):EvidenceRef=>({kind:'record',url,recordSource:source,note});
export async function enrichPublicRecords(result:AnalysisResult):Promise<AnalysisResult>{const mailto=process.env.OPENALEX_MAILTO;if(!mailto)return result;result.mode.publicRecords=true;const doiCitations=result.citations.filter(c=>c.doi).slice(0,12);if(!doiCitations.length)return result;
 const records=await Promise.all(doiCitations.map(async citation=>({citation,work:await getWork(citation.doi!,mailto)})));const successfulKeys=new Set<string>();const calls:AnalysisResult['privacy']['externalCalls']=[];
 const addEntity=(name:string,type:AnalysisResult['entities'][number]['type'],evidence:EvidenceRef)=>{let entity=result.entities.find(e=>e.name.toLowerCase()===name.toLowerCase()&&e.type===type);if(!entity){entity={id:`public-${result.entities.length+1}`,type,name,aliases:[],refs:[evidence]};result.entities.push(entity);}else if(!entity.refs.some(r=>r.url===evidence.url))entity.refs.push(evidence);return entity;};
 for(const {citation,work} of records){const {crossref,openalex,urls}=work;let crossOk=false,openOk=false;if(crossref){const msg=obj(crossref.message);const crTitle=str(array(msg.title)[0]);const note=crTitle?`Crossref work metadata: ${crTitle}`:`Crossref metadata for DOI ${citation.doi}`;citation.refs.push(recordRef('crossref',urls.crossref,note));crossOk=true;const funders=array(msg.funder);for(const raw of funders){const name=str(obj(raw).name);if(name)addEntity(name,'funder',recordRef('crossref',urls.crossref,`Crossref lists ${name} as a funder.`));}}
  if(openalex){citation.refs.push(recordRef('openalex',urls.openalex,`OpenAlex work metadata for DOI ${citation.doi}`));openOk=true;const workRecord=obj(openalex);const title=str(workRecord.title);const authorships=array(workRecord.authorships);for(const item of authorships){const authorship=obj(item),authorData=obj(authorship.author),authorName=str(authorData.display_name);if(!authorName)continue;const authorRef=recordRef('openalex',urls.openalex,`OpenAlex lists ${authorName} as a work author.`);const author=addEntity(authorName,'person',authorRef);for(const rawInst of array(authorship.institutions)){const name=str(obj(rawInst).display_name);if(!name)continue;const orgRef=recordRef('openalex',urls.openalex,`OpenAlex lists ${name} as an author affiliation${title?` for ${title}`:''}.`);const organization=addEntity(name,'organization',orgRef);result.relations.push({from:author.id,to:organization.id,type:'affiliated_with',refs:[orgRef]});if(!result.findings.some(f=>f.type==='affiliation_documented'&&f.evidence.some(e=>e.url===urls.openalex&&e.note===orgRef.note)))result.findings.push({id:`public-affiliation-${author.id}-${organization.id}`,type:'affiliation_documented',label:'FACT',severity:'info',title:'Affiliation listed in public record',whatWasFound:`${authorName} is listed with ${name} in OpenAlex metadata.`,whyItMatters:'Public metadata can help trace affiliations; these records may be incomplete or out of date.',uncertainty:'The public record reflects its metadata at the time checked.',recommendedActions:['Confirm the affiliation with the paper and institution record.'],evidence:[orgRef],graphNodeIds:[]});}}
  }
  if(crossOk||openOk)successfulKeys.add(citation.key);calls.push({service:'Crossref',purpose:crossOk?`Verify metadata for DOI ${citation.doi}`:`DOI lookup unavailable for ${citation.doi}`,redactions:{}});calls.push({service:'OpenAlex',purpose:openOk?`Verify work and affiliation metadata for DOI ${citation.doi}`:`DOI lookup unavailable for ${citation.doi}`,redactions:{}});
 }
 if(successfulKeys.size){const verifiedClaims=new Set(result.claims.filter(c=>c.citationKeys.some(k=>successfulKeys.has(k))).map(c=>c.id));result.findings=result.findings.filter(f=>f.type!=='untraced_statistic'||!result.claims.some(c=>verifiedClaims.has(c.id)&&c.refs.some(r=>f.evidence.some(e=>e.quote===r.quote))));}
 for(const {citation,work} of records){if(work.crossref||work.openalex){const id=`record-${citation.key}`;const label=`Public record · DOI ${citation.doi}`;if(!result.graph.nodes.some((n:unknown)=>obj(n).id===id)){result.graph.nodes.push({id,type:'evidenceNode',position:{x:1280,y:result.graph.nodes.length*75},data:{label,kind:'document'}});}result.graph.edges.push({id:`cite-record-${citation.key}`,source:`cite-${citation.key}`,target:id,label:'public record'});}}
 result.privacy.externalCalls.push(...calls);result.findings=validateFindings(result.findings,result.docs);result.score=scoreFindings(result.findings);return result;
}
