'use client';
import {useEffect,useRef,useState} from 'react';
import {EvidenceGraph} from './EvidenceGraph';
import type {AnalysisResult} from '@/lib/types';
export default function Home(){
 const [result,setResult]=useState<AnalysisResult|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[drag,setDrag]=useState(false),[status,setStatus]=useState({llm:false,publicRecords:false,voice:false}),[activeTab,setActiveTab]=useState<'symptoms'|'chain'>('symptoms'),[selectedFindingId,setSelectedFindingId]=useState<string|null>(null);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{fetch('/api/status').then(r=>r.json()).then(setStatus).catch(()=>{});},[]);
 async function demo(){await run('/api/demo');}
 async function run(url:string,files?:File[]){setBusy(true);setError('');try{let response:Response;if(files){const fd=new FormData();files.forEach(f=>fd.append('files',f));fd.set('primaryIndex','0');response=await fetch('/api/analyze',{method:'POST',body:fd});}else response=await fetch(url);const data=await response.json();if(!response.ok)throw new Error(data.error??'The analysis could not be completed.');setResult(data);}catch(e){setError(e instanceof Error?e.message:'The analysis could not be completed.');}finally{setBusy(false);}}
 function filesChosen(files:FileList|null){if(files?.length)void run('/api/analyze',Array.from(files));}
 const labelTone=(label:string)=>label==='POTENTIAL_CONCERN'?'concern':label==='UNKNOWN'?'unknown':label==='INTERPRETATION'?'interpretation':'fact';
 return <main className="shell">
 <header className="top"><div className="brand"><span className="mark">ED</span><span>EvidenceDoctor</span></div><a href="#about">About the review</a></header>
 {!result?<section className="intake"><p className="eyebrow">EVIDENCE INVESTIGATION · CYBERSECURITY & PRIVACY</p><h1>Before you trust the evidence, investigate the evidence behind it.</h1><p className="lede">Review a report and the sources it cites. EvidenceDoctor highlights what can be checked, what needs more context, and hidden instructions aimed at AI reviewers.</p>
 <div className={`drop ${drag?'drag':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);filesChosen(e.dataTransfer.files)}}><div className="fileicon">↑</div><h2>Choose a report and its cited sources</h2><p>PDF, .txt or .md · up to 10 MB per file · 6 files maximum</p><button className="button secondary" onClick={()=>input.current?.click()} disabled={busy}>Browse files</button><input ref={input} hidden type="file" multiple accept=".pdf,.txt,.md,application/pdf,text/plain,text/markdown" onChange={e=>filesChosen(e.target.files)}/></div>
 <div className="actionrow"><button className="button" onClick={demo} disabled={busy}>{busy?'Investigating…':'Run demo case'}</button><a className="download" href="/demo/primary-report.pdf" download>Download demo PDF ↓</a></div>
 {error&&<div role="alert" className="error"><b>We couldn’t analyze that document</b><p>{error}</p></div>}
 <div className="privacy"><span className="lock">◈</span><span><b>Processed in memory. Nothing is stored.</b><br/>AI extraction: {status.llm?'on':'off'} · Public record checks: {status.publicRecords?'on':'off'}</span></div>
 </section>:<section className="results">
 <div className="resulthead"><div><p className="eyebrow">INVESTIGATION REPORT</p><h1>Patient: {result.docs.find(d=>d.role==='primary')?.pages[0]?.text.match(/^#\s*(.+)$/m)?.[1]??result.docs.find(d=>d.role==='primary')?.fileName}</h1><p className="muted">{result.docs.length} document{result.docs.length===1?'':'s'} reviewed · analysis completed in memory</p></div><button className="button secondary" onClick={()=>{setResult(null);setError('')}}>New review</button></div>
 <div className="scoregrid"><div className="scorecard"><div className="ring" style={{'--score':`${result.score.overall}%`} as React.CSSProperties}><span>{result.score.overall}</span></div><div><h2>Evidence Health</h2><p>This score summarizes what the investigation found. It is not a measure of truth and has not been scientifically validated.</p></div></div><div className="categories">{result.score.categories.map(c=><details key={c.name}><summary><span>{c.name}</span><b>{c.score}</b></summary><div className="bar"><i style={{width:`${c.score}%`}}/></div>{c.reasons.length>0?<ul>{c.reasons.map(r=><li key={r}>{r}</li>)}</ul>:<p>No score deductions in this category.</p>}</details>)}</div></div>
 {result.findings.filter(f=>f.type==='hidden_instruction').map(f=><article className="hiddenalert" key={f.id}><div className="alerticon">!</div><div><p className="eyebrow">HIDDEN TEXT REVEALED · PAGE {f.evidence[0]?.page}</p><h2>{f.title}</h2><blockquote>{f.evidence[0]?.quote}</blockquote><button className="textbutton" onClick={()=>{setSelectedFindingId(f.id);setActiveTab('chain')}}>Trace this finding in the evidence chain →</button><p>Detection method: {f.evidence[0]?.method}. Hidden text was excluded from claim extraction.</p><Evidence f={f}/></div></article>)}
 <div className="tabrow" role="tablist" aria-label="Investigation views"><button role="tab" aria-selected={activeTab==='symptoms'} className={activeTab==='symptoms'?'selected':''} onClick={()=>setActiveTab('symptoms')}>Symptoms</button><button role="tab" aria-selected={activeTab==='chain'} className={activeTab==='chain'?'selected':''} onClick={()=>setActiveTab('chain')}>Evidence chain</button><span>{result.findings.length} findings · {result.graph.nodes.length} graph nodes</span></div>
 {activeTab==='symptoms'?<div className="findings">{[...result.findings].filter(f=>f.type!=='hidden_instruction').sort((a,b)=>({high:0,medium:1,low:2,info:3}[a.severity]-({high:0,medium:1,low:2,info:3}[b.severity]))).map(f=><article className="finding" key={f.id}><div className="findingtop"><span className={`chip ${labelTone(f.label)}`}>{f.label.replace('_',' ')}</span><span className="severity">{f.severity}</span></div><h3>{f.title}</h3><p>{f.whatWasFound}</p><div className="why"><b>Why it matters</b><p>{f.whyItMatters}</p></div><p className="uncertain">{f.uncertainty}</p><details><summary>Show evidence ({f.evidence.length})</summary><Evidence f={f}/></details><button className="textbutton" onClick={()=>{setSelectedFindingId(f.id);setActiveTab('chain')}}>Trace finding in evidence chain →</button></article>)}</div>:<EvidenceGraph result={result} selectedFindingId={selectedFindingId}/> }
 <div className="sectiontitle"><div><p className="eyebrow">NEXT STEPS</p><h2>Treatment</h2></div></div><div className="treatment">{[...new Set(result.findings.flatMap(f=>f.recommendedActions))].map((a,i)=><label key={i}><input type="checkbox"/><span>{a}</span></label>)}</div>
 <div className="twocol"><section><div className="sectiontitle"><div><p className="eyebrow">PIPELINE</p><h2>Lab log</h2></div></div><div className="log">{result.labLog.map((l,i)=><div key={i}><span>{l.stage}</span><span>{l.detail}</span><b>{l.ms} ms</b></div>)}</div></section><section><div className="sectiontitle"><div><p className="eyebrow">DATA HANDLING</p><h2>Privacy receipt</h2></div></div><div className="receipt"><b>{result.privacy.statement}</b><p>Stored: no</p><p>{result.privacy.externalCalls.length?result.privacy.externalCalls.map(x=>`${x.service}: ${x.purpose}`).join(' · '):'No external services were contacted.'}</p></div></section></div>
 <div className="printrow"><button className="button secondary" onClick={()=>window.print()}>Print report</button></div>
 </section>}
 <footer id="about">EvidenceDoctor does not tell you what to believe. It tells you what to investigate before you believe it.<span>Privacy first · Documents are analyzed in memory</span></footer>
 </main>
}
function Evidence({f}:{f:AnalysisResult['findings'][number]}){return <ul className="evidence">{f.evidence.map((e,i)=><li key={i}>{e.kind==='quote'?<><blockquote>“{e.quote}”</blockquote><span>{e.fileName}{e.page?` · page ${e.page}`:''}{e.method?` · ${e.method}`:''}</span></>:<a href={e.url} target="_blank" rel="noreferrer">{e.note??e.url}</a>}</li>)}</ul>}
